import type { Metadata } from "next";
import { Geist, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import Footer from "./footer";
import localFont from "next/font/local";
import Nav from "./components/nav";
// import l from "../public/font/m"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const myCustomFont = localFont({
  src: "../public/font/HelveticaNeueBlack.otf",
  display: "swap",
  weight: "500",
  style: "medieum",
  variable: "--font-helvetica",
});

const brick = Bricolage_Grotesque({
  variable: "--font-bricolage-mono",
  weight: ["500", "800", "400", "600", "700", "200", "300"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${brick.variable} ${myCustomFont.variable} bg-white mt-7 font-helvetica`}
      >
        <main className="min-h-screen mx-auto max-w-[1440px]">
          <Nav />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
