import type { Metadata } from "next";
import {
  Geist,
  Bricolage_Grotesque,
  Shadows_Into_Light,
} from "next/font/google";
import "./globals.css";
import Footer from "./footer";
import localFont from "next/font/local";
import Nav from "./components/nav";
// import l from "../public/font/m"
const shadowsIntoLight = Shadows_Into_Light({
  variable: "--font-shadows-into-light",
  subsets: ["latin", "latin-ext"],
  weight: ["400"],
});

const myCustomFont = localFont({
  src: "../public/font/HelveticaNeueBlack.otf",
  display: "swap",
  weight: "500",
  style: "medieum",
  variable: "--font-helvetica",
});

const brick = Bricolage_Grotesque({
  variable: "--font-bricolage-mono",
  weight: ["500", "800", "400", "600", "700", "200", "300"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${brick.variable} ${shadowsIntoLight.variable} ${myCustomFont.variable} bg-[#F4F2FB] mt-7 font-helvetica`}
      >
        <main className="min-h-screen max-w-[1440px] mx-[32px] md:mx-[40px] xl:mx-[120px]">
          <Nav />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
