import type { Metadata } from "next";
import {
  Geist,
  Bricolage_Grotesque,
  Shadows_Into_Light,
} from "next/font/google";
import "./globals.css";
import Footer from "./footer";
import localFont from "next/font/local";
import Nav from "./components/nav";

const shadowsIntoLight = Shadows_Into_Light({
  variable: "--font-shadows-into-light",
  subsets: ["latin", "latin-ext"],
  weight: ["400"],
});

const myCustomFont = localFont({
  src: "../public/font/HelveticaNeueBold.otf",
  display: "swap",
  weight: "500",
  style: "medieum",
  variable: "--font-helvetica",
});

const myCustomFont400 = localFont({
  src: "../public/font/HelveticaNeueThin.otf",
  display: "swap",
  weight: "400",
  style: "medieum",
  variable: "--font-helvetica400",
});

const brick = Bricolage_Grotesque({
  variable: "--font-bricolage-mono",
  weight: ["500", "800", "400", "600", "700", "200", "300"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${brick.variable} ${myCustomFont400.variable} ${shadowsIntoLight.variable} ${myCustomFont.variable} bg-[#F4F2FB] mt-7 font-helvetica px-5 [1440px]:px-0`}
      >
        <main className="min-h-screen max-w-[1440px] mx-auto">
          <Nav />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
